# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardware', '0016_auto_20180220_2123'),
        ('pin', '0002_auto_20180220_2024'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, b'Other'), (2, b'Temperature'), (3, b'Movement')], default=3)),
                ('image', models.FileField(default='', upload_to=b'')),
                ('scheme_image', models.FileField(default='', upload_to=b'')),
                ('code', models.CharField(default='', max_length=100)),
                ('last_request_time', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(blank=True, max_length=200)),
                ('devices', models.ManyToManyField(blank=True, to='hardware.Device')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin.Pin')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.Sensor')),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
