# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-11 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_sensor_fake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='pin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pin.Pin'),
        ),
    ]
