# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-11 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0018_schedule'),
        ('sensor', '0003_auto_20180311_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Device')),
            ],
        ),
        migrations.AlterField(
            model_name='sensor',
            name='devices',
            field=models.ManyToManyField(blank=True, through='sensor.Sensor_Devices', to='hardware.Device', verbose_name='Devices'),
        ),
        migrations.AddField(
            model_name='sensor_devices',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.Sensor'),
        ),
    ]
