# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_sensor_devices_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_devices',
            name='type',
            field=models.IntegerField(choices=[(1, b'Heater'), (2, b'Cooling'), (3, b'Light')], default=1),
        ),
    ]
