# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(default='', upload_to=b'')),
                ('scheme_image', models.FileField(default='', upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('is_in', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Forth'), ('5', 'Fifth'), ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eughth')])),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Device')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Pin')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(default='', upload_to=b'')),
                ('scheme_image', models.FileField(default='', upload_to=b'')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Pin')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='pin',
            field=models.ManyToManyField(through='hardware.Relay', to='hardware.Pin'),
        ),
    ]
