# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_auto_20171210_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='relay',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='relay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hardware.Relay'),
            preserve_default=False,
        ),
    ]
