# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_auto_20180122_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='is_active',
        ),
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
