# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_auto_20180127_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='devices',
            field=models.ManyToManyField(to='hardware.Device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cropped_image',
            field=image_cropping.fields.ImageRatioField('image', '422x422', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropped image'),
        ),
    ]
