# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_auto_20180203_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='devices',
            field=models.ManyToManyField(blank=True, to='hardware.Device'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='last_request_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
