# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_auto_20180203_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='last_request_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
