# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_auto_20180203_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField()),
                ('temperature', models.IntegerField(null=True)),
                ('humidity', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.IntegerField(choices=[(1, b'Temperature'), (2, b'Movement'), (3, b'Other')], default=3),
        ),
        migrations.AddField(
            model_name='temperaturehistory',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.Sensor'),
        ),
    ]
