# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0011_auto_20180204_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.IntegerField(choices=[(1, b'Other'), (2, b'Temperature'), (3, b'Movement')], default=3),
        ),
        migrations.AlterField(
            model_name='temperaturehistory',
            name='humidity',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='temperaturehistory',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
