# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0012_auto_20180204_2234'),
    ]

    database_operations = [
        migrations.AlterModelTable('Pin', 'pin_pin'),
        migrations.AlterModelTable('Relay', 'relay_relay')
    ]

    state_operations = [
        migrations.DeleteModel('Pin'),
        migrations.AlterField(
            model_name='device',
            name='pin',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='pin', to='pin.Pin'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pin',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='pin', to='pin.Pin'),
        ),
        migrations.DeleteModel('Relay'),
        migrations.AlterField(
            model_name='device',
            name='relay',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='relay', to='relay.Relay'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
