# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0013_auto_20180220_0941'),
        ('hardware', '0014_auto_20180220_2041'),
    ]

    operations = [
    ]
