# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0016_auto_20180220_2123'),
    ]
    stateOperations = [
        migrations.RemoveField(
            model_name='sensor',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='temperaturehistory',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='TemperatureHistory',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(None, state_operations=stateOperations)
    ]
