# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0018_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device', models.ManyToManyField(to='hardware.Device')),
            ],
        ),
    ]
