# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardware', '0013_auto_20180220_0941')
    ]

    state_operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('is_in', models.BooleanField(default=True)),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 'pin_pin',
            },
            bases=(models.Model,),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
