# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pin', '0001_initial')
    ]

    state_operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(
                    choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Forth'), ('5', 'Fifth'),
                             ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eighth')])),
                ('device', models.ForeignKey(on_delete=models.deletion.CASCADE, to='hardware.Device')),
                ('pin', models.ForeignKey(on_delete=models.deletion.CASCADE, to='pin.Pin')),
            ],
            options={
                'db_table': 'relay_relay',
            },
            bases=(models.Model,),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
