# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-11 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0003_remove_relay_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relay',
            name='number',
            field=models.IntegerField(choices=[(1, b'First'), (2, b'Second'), (3, b'Third'), (4, b'Forth'), (5, b'Fifth'), (6, b'Sixth'), (7, b'Seventh'), (8, b'Eighth')], unique=True),
        ),
    ]
